### PR TITLE
Re-word the explanation of the GridCF

### PR DESCRIPTION
**Pull request by brianhlin**
I think we added a few too many words in our initial sentence or maybe we're missing a few words? As it stands it's a bit confusing

### CODE REVIEW

**Review by msalle — CHANGES_REQUESTED** [review]
Perhaps good to keep the global community as in "...is a global community that provides support...". Not sure what the original intend was.

**Review by fscheiner — CHANGES_REQUESTED** [review]
I'd back Mischa's proposal. That "global community" has just a nice touch we shouldn't give away too easily.

**Comment by matyasselmeci** [comment]
Having both "global community" and "global grid community" in the same sentence looks redundant IMO. How about

"The Grid Community Forum (GridCF) is a global community that provides support for core grid software."

**Comment by fscheiner** [comment]
Right, that's a little bit too much *global community*. I haven't really imagined the whole sentence. I'm fine with your rephrasing, Matyas. It also better matches the subtitle of the page ("Community-based support for core software packages in grid computing").

**Comment by msalle** [comment]
I also fully agree with Matyas' suggested rephrasing.

**Comment by brianhlin** [comment]
Updated with Mat's phrasing and also fixed some other spelling errors

**Review by msalle — APPROVED** [review]

**Review by fscheiner — APPROVED** [review]

**Pull request merged**
