### PR TITLE
Add paragraph for news and announcements

### PR DESCRIPTION
**Pull request by fscheiner**
Let's start small and just add a paragraph for news and announcements. Later we can move this to a separate page and maybe add sort of a menu to the main `index.md`.

### CODE REVIEW

**Comment by msalle** [comment]
Hi, in principle fine, but aren't there more generic links we could use?
Also perhaps good to start with EPEL (which is probably the most widely used)?

**Review by bbockelm — APPROVED** [review]
LGTM.

**Comment by fscheiner** [comment]
@msalle wrote
> Hi, in principle fine, but aren't there more generic links we could use?

I just took Mattias' announcement from 2018-09-24 on the gt-eos mailing list verbatim. What do you have in mind with more generic links? Yes, the Debian  link also includes other packages, but I assume there is no better view available there. The Fedora/EPEL links are better in that they're limited to Globus packages IMHO. 

> Also perhaps good to start with EPEL (which is probably the most widely used)?

I don't have a preference for the order and am fine with putting EPEL on top. I can change that together with any more generic links you provide, ok?

**Comment by msalle** [comment]
Hi, I couldn't find any more generic links (hence the question (-: ), not sure there is one. Perhaps a link to https://packages.debian.org/search?suite=buster&searchon=all&keywords=GridCF ?
I'm wondering if it would be possible to create a new tag or section for Debian.
In any case, I would say just leave it for now.

**Comment by fscheiner** [comment]
@msalle 
I see. I changed the link for Debian to the one you provided and put the EPEL links on top. For new tags or sections in Debian I'm unsure if this is easy to get accepted. Currently I see Globus/GridCF packages below "Network", "Libraries" and "Library development" and possibly others.

As this is no major change to the original PR I'll merge this right away without prior request for review.

**Pull request merged**
